### ISSUE TITLE
WAP4410N

### ISSUE THREAD

**Issue by Matthew1471** [elvanderb/TCP-32764#11]
Listens to port and responds to data with "ScMM" but your Python script doesn't work in its current form.

PID VID:    WAP4410N-E V02
Software Version:   2.0.6.1

**Comment by gpread** [comment]
> Listens to port and responds to data with "ScMM" but your Python script doesn't work in its current form.
> 
> PID VID: WAP4410N-E V02 Software Version: 2.0.6.1

Hi, @matthew1471 

I am looking for a 2.0.6.1 or newer firmware image file for a WAP4410N-E V02 that I have.  Cisco made this device unsupported in 2019 and so I am unable to find one through an official channel.  Any chance that you have it, and can upload somewhere that I could download from, so I can update my device ?   Thanks in advance, Gavin
