### ISSUE TITLE
Vulnerable

### ISSUE THREAD

**Issue by SilentT-FR** [elvanderb/TCP-32764#44]
DG834   V5.01.09 Yes - Via Wan (Internet)
Cisco WAP4410N-E V02    2.0.1.0 Yes - Via Wan (Internet)
Cisco WAP4410N-E V02    2,0,2,1 Yes - Via Wan (Internet)
Cisco WAP4410N-E V02    2.0.3.3 Yes - Via Wan (Internet)
Cisco WAP4410N-E V02    2.0.4.2 Yes - Via Wan (Internet)
Cisco WAP4410N-E V02    2.0.5.3 Yes - Via Wan (Internet)
Cisco WAP4410N-E V02    2.0.6.1 Yes - Via Wan (Internet)
Netgear DGN2000              1.1.1   Yes - Via Wan (Internet)
Netgear DGN2000 1.1.11.0    Yes - Via Wan (Internet)
Netgear DGN2000             1.3.10.0 (North America) Yes - Via Wan (Internet)
Netgear DGN2000             1.3.11.0 (North America) Yes - Via Wan (Internet)
Netgear DGN2000         1.3.12.0 (North America)    Yes - Via Wan (Internet)

**Comment by TekBear** [comment]
@SilentT-FR 
looking on Netgear.com (http://downloadcenter.netgear.com/en/product/DG834Gv2#searchResults) I found no information about any release of DG834GV2 firmware V3.01.38 the last release was V3.01.29
Are you sure it was V3.01.38 ?

**Comment by SilentT-FR** [comment]
Sorry is only for the v1 ans UK VERSION http://downloadcenter.netgear.com/en/product/DG834v1#searchResults

Envoyé de mon iPhone

**Comment by TekBear** [comment]
@SilentT-FR  I looked at the file http://downloadcenter.netgear.com/en/product/DG834v1#searchResults
and grabbed the file. It  mixes v1 and v2 this is confusing.
> DG834 and DG834G Firmware Version 3.01.38 (for use in UK only).zip
> Contains:
>    * ReleaseNotes_DG834v1_fw_3.01.38.html
>    * dg834v2_dg834gv2_3_01_38_uk_only.zip (contains DG834GV2_V3.01.38.img)
